import {StateSchema,StateGraph,START,END,} from "@langchain/langgraph";
import type { GraphNode } from "@langchain/langgraph";
import { HumanMessage } from "@langchain/core/messages";
import z from "zod";
import { geminiModel, mistralModel, cohereModel } from "./model.service.js";

const State = new StateSchema({
  problem: z.string().default(""),
  solution_1: z.string().default(""),
  solution_2: z.string().default(""),
  judgement: z.object({
    solution_1_score: z.number().default(0),
    solution_2_score: z.number().default(0),
    solution_1_reasoning: z.string().default(""),
    solution_2_reasoning: z.string().default(""),
  }),
});

const solutionNode: GraphNode<typeof State> = async (state) => {

  const [mistralResponse, cohereResponse] = await Promise.all([
    mistralModel.invoke(state.problem),
    cohereModel.invoke(state.problem),
  ]);

  return {
    solution_1: mistralResponse.text,
    solution_2: cohereResponse.text,
  };

};

const judgementNode: GraphNode<typeof State> = async (state) => {
  const { problem, solution_1, solution_2 } = state;

  const structuredGemini = geminiModel.withStructuredOutput(
    z.object({
      solution_1_score: z.number().min(0).max(10),
      solution_2_score: z.number().min(0).max(10),
      solution_1_reasoning: z.string(),
      solution_2_reasoning: z.string(),
    }),
  );

  const judgeResponse = await structuredGemini.invoke([
    new HumanMessage(`You are a judge tasked with evaluating two solutions generated by different AI models. Please provide a score out of 10 for each solution, along with your reasoning for the scores.

    Problem: ${problem}
    Solution 1: ${solution_1}
    Solution 2: ${solution_2}

    Please evaluate the solutions and provide scores and reasoning.`),
  ]);

  const {
    solution_1_score,
    solution_2_score,
    solution_1_reasoning,
    solution_2_reasoning,
  } = judgeResponse;

  return {
    judgement: {
      solution_1_score,
      solution_2_score,
      solution_1_reasoning,
      solution_2_reasoning,
    },
  };
};

const graph = new StateGraph(State)
  .addNode("solution", solutionNode)
  .addNode("judgement_node", judgementNode)
  .addEdge(START, "solution")
  .addEdge("solution", "judgement_node")
  .addEdge("judgement_node", END)
  .compile();

export default async function (problem: string) {
  const results = await graph.invoke({
    problem: problem,
  });
  return results;
}
