import { StateSchema, StateGraph, START, END } from "@langchain/langgraph";
import type { GraphNode } from "@langchain/langgraph";
import { HumanMessage } from "@langchain/core/messages";
import z from "zod";
import { geminiModel, mistralModel, cohereModel } from "../model.service.js";
import { State } from "./state.js";
import { fileProcessingNode } from "../nodes/file-processing.node.js";
import { chunkingNode } from "../nodes/chunking.node.js";
import { embeddingNode } from "../nodes/embedding.node.js";
import { retrievalNode } from "../nodes/retrieval.node.js";

const solutionNode: GraphNode<typeof State> = async (state) => {
  const prompt = ` You are answering questions about an uploaded document. Use ONLY the provided context. 
  If the answer is not found in the context, say you could not find enough information. 
  
  CONTEXT: ${state.retrieved_context.join("\n\n")} 
  
  QUESTION: ${state.problem} `;
  const [mistralResponse, cohereResponse] = await Promise.all([
    mistralModel.invoke(prompt),
    cohereModel.invoke(prompt),
  ]);

  return {
    solution_1: mistralResponse.text,
    solution_2: cohereResponse.text,
  };
};

const judgementNode: GraphNode<typeof State> = async (state) => {
  const { problem, solution_1, solution_2 } = state;

  const structuredGemini = geminiModel.withStructuredOutput(
    z.object({
      solution_1_score: z.number().min(0).max(10),
      solution_2_score: z.number().min(0).max(10),
      solution_1_reasoning: z.string(),
      solution_2_reasoning: z.string(),
    }),
  );

  const judgeResponse = await structuredGemini.invoke([
    new HumanMessage(`You are a judge tasked with evaluating two solutions generated by different AI models. Please provide a score out of 10 for each solution, along with your reasoning for the scores.

    Problem: ${problem}
    Solution 1: ${solution_1}
    Solution 2: ${solution_2}

    Please evaluate the solutions and provide scores and reasoning.`),
  ]);

  const {
    solution_1_score,
    solution_2_score,
    solution_1_reasoning,
    solution_2_reasoning,
  } = judgeResponse;

  return {
    judgement: {
      solution_1_score,
      solution_2_score,
      solution_1_reasoning,
      solution_2_reasoning,
    },
  };
};

const graph = new StateGraph(State)
  .addNode("file_processing", fileProcessingNode)
  .addNode("chunking", chunkingNode)
  .addNode("embedding", embeddingNode)
  .addNode("retrieval", retrievalNode)
  .addNode("solution", solutionNode)
  .addNode("judgement_node", judgementNode)
  .addEdge(START, "file_processing")
  .addEdge("file_processing", "chunking")
  .addEdge("chunking", "embedding")
  .addEdge("embedding", "retrieval")
  .addEdge("retrieval", "solution")
  .addEdge("solution", "judgement_node")
  .addEdge("judgement_node", END)
  .compile();

export default async function ({
  problem,
  uploaded_file_path,
}: {
  problem: string;
  uploaded_file_path?: string;
}) {
  const results = await graph.invoke({
    problem,
    uploaded_file_path,
  });

  return results;
}
