import { StateGraph, START, END } from "@langchain/langgraph";
import type { GraphNode } from "@langchain/langgraph";
import { HumanMessage } from "@langchain/core/messages";
import z from "zod";

import { State } from "./state.js";

import { geminiModel, mistralModel, cohereModel } from "../model.service.js";

import { fileProcessingNode } from "../nodes/file-processing.node.js";
import { chunkingNode } from "../nodes/chunking.node.js";
import { embeddingNode } from "../nodes/embedding.node.js";
import { retrievalNode } from "../nodes/retrieval.node.js";

const solutionNode: GraphNode<typeof State> = async (state) => {
  const prompt =
    state.retrieved_context.length > 0
      ? `
You are answering questions about an uploaded document.

Use ONLY the provided context.

If the answer is not found in the context,
say you could not find enough information.

CONTEXT:
${state.retrieved_context.join("\n\n")}

QUESTION:
${state.problem}
`
      : state.problem;

  state.sendEvent?.("status", "Generating response....");

  let solution1 = "";
  let solution2 = "";
  const mistralTask = async () => {
    state.sendEvent?.("model_1_start", null);
    const stream = await mistralModel.stream(prompt);
    for await (const chunk of stream) {
      const text = typeof chunk.content === "string" ? chunk.content : "";
      solution1 += text;
      state.sendEvent?.("model_1_chunk", text);
    }
  };
  const cohereTask = async () => {
    state.sendEvent?.("model_2_start", null);
    const stream = await cohereModel.stream(prompt);
    for await (const chunk of stream) {
      const text = typeof chunk.content === "string" ? chunk.content : "";
      solution2 += text;
      state.sendEvent?.("model_2_chunk", text);
    }
  };
  await Promise.all([mistralTask(), cohereTask()]);
  return { solution_1: solution1, solution_2: solution2 };
};

const judgementNode: GraphNode<typeof State> = async (state) => {
  const { problem, solution_1, solution_2 } = state;
  state.sendEvent?.("judge_start", null);

  const structuredGemini = geminiModel.withStructuredOutput(
    z.object({
      solution_1_score: z.number().min(0).max(10),

      solution_2_score: z.number().min(0).max(10),

      solution_1_reasoning: z.string(),

      solution_2_reasoning: z.string(),
    }),
  );

  const judgeResponse = await structuredGemini.invoke([
    new HumanMessage(`
You are a judge tasked with evaluating two solutions generated by different AI models.

Provide:

- Score out of 10
- Reasoning

Problem:
${problem}

Solution 1:
${solution_1}

Solution 2:
${solution_2}
`),
  ]);

  state.sendEvent?.("judge_result", judgeResponse);

  return {
    judgement: {
      solution_1_score: judgeResponse.solution_1_score,

      solution_2_score: judgeResponse.solution_2_score,

      solution_1_reasoning: judgeResponse.solution_1_reasoning,

      solution_2_reasoning: judgeResponse.solution_2_reasoning,
    },
  };
};

const graph = new StateGraph(State)

  .addNode("file_processing", fileProcessingNode)

  .addNode("chunking", chunkingNode)

  .addNode("embedding", embeddingNode)

  .addNode("retrieval", retrievalNode)

  .addNode("solution", solutionNode)

  .addNode("judgement_node", judgementNode)

  .addConditionalEdges(
    START,
    (state) => {
      if (state.uploaded_file_path) {
        return "rag";
      }

      return "normal";
    },
    {
      rag: "file_processing",
      normal: "solution",
    },
  )

  .addEdge("file_processing", "chunking")

  .addEdge("chunking", "embedding")

  .addEdge("embedding", "retrieval")

  .addEdge("retrieval", "solution")

  .addEdge("solution", "judgement_node")

  .addEdge("judgement_node", END)

  .compile();

export default async function ({
  problem,
  uploaded_file_path,
  sendEvent,
}: {
  problem: string;
  uploaded_file_path?: string;
  sendEvent?: (type: string, data: unknown) => void;
}) {
  const results = await graph.invoke({
    problem,
    uploaded_file_path,
    sendEvent,
  });
  return results;
}
